package tech.hadenw.shmamesbot.brain;

public enum BotSettingName {
	PIN_CHANNEL,
	DEV_ANNOUNCE_CHANNEL,
	DO_PIN,
	REMOVAL_EMOTE,
	REMOVAL_THRESHOLD,
	APPROVAL_THRESHOLD,
	APPROVAL_EMOTE,
	ALLOW_MODIFY
}
