package tech.hadenw.discordbot.brain;

public enum BotSettingName {
	PIN_CHANNEL,
	DEV_ANNOUNCE_CHANNEL,
	MUTE_DEV_ANNOUNCES,
	PIN_POLLS,
	REMOVAL_EMOTE,
	REMOVAL_THRESHOLD,
	APPROVAL_THRESHOLD,
	APPROVAL_EMOTE,
	ALLOW_MODIFY
}
